### ISSUE TITLE
Can't seem to find the GTK C# documentation anywhere

### ISSUE THREAD

**Issue by dunestorm333** [GtkSharp/GtkSharp#124] opened 2019-12-21 09:36 UTC
Is there a reference guide or a doc somewhere specific to GTK#? I've scoured lots of different sources but am unable to find a doc which lists all the properties of Labels and Buttons for example. The only docs I can find are specific to C/C++ which are useless for GTK#. Am I just being dumb?

**Comment by cra0zy** [comment] 2019-12-21 11:16
No docs are available. This is kind of duplicate of: https://github.com/GtkSharp/GtkSharp/issues/66

**Closed by cra0zy** 2019-12-21 11:16 UTC
