### ISSUE TITLE
Question: Is there any Plan to support Gtk4?

### ISSUE THREAD

**Issue by litch0** [GtkSharp/GtkSharp#213] opened 2021-01-21 07:32 UTC
Is there any Plan to support Gtk4?
I heard that the rust bindings to gtk4 are already done, so I think there is the c, c++ and rust apis that can be used to make the c# api. so I am curious to see what you guys will choose

**Comment by lytico** [comment] 2021-01-21 14:04
duplicate of #166

**Closed by lytico** 2021-01-21 14:04 UTC
Labels: duplicate
