### ISSUE TITLE
Step Up your game and support gtk4

### ISSUE THREAD

**Issue by MXP2095onetechguy** [GtkSharp/GtkSharp#244] opened 2021-05-03 08:19 UTC
This gtk sharp support gtk 3 unlike the mono  version, but c'mon, this gtksharp is now like the mono version except that it support gtk3, go support gtk4

**Comment by harry-cpp** [comment] 2021-05-03 10:21
Duplicate of https://github.com/GtkSharp/GtkSharp/issues/166

**Closed by harry-cpp** 2021-05-03 10:21 UTC
