### ISSUE TITLE
browser widget

### ISSUE THREAD

**Issue by ReaperOfSouls1909** [GtkSharp/GtkSharp#137] opened 2020-02-17 21:50 UTC
do you guys have a browser widget it's needed in ryujinx project for an offline applet for games for manuals and accepting *Licensing Agreements

**Comment by harry-cpp** [comment] 2020-02-17 22:43
Duplicate of: https://github.com/GtkSharp/GtkSharp/issues/109

TLDR. No Webkit 2 support on Windows :/ Technically I can setup a repo with webkit 1, but than Linux distros are missing a package for it. I really have no good solution.

**Closed by harry-cpp** 2020-02-17 22:43 UTC
