### ISSUE TITLE
libhandy support

### ISSUE THREAD

**Issue by archanox** [GtkSharp/GtkSharp#144] opened 2020-03-27 23:39 UTC
Is it at all possible to incorporate libhandy into GtkSharp projects?

https://gitlab.gnome.org/Community/Purism/libhandy
https://source.puri.sm/Librem5/libhandy

**Comment by harry-cpp** [comment] 2020-03-27 23:48
Duplicate of https://github.com/GtkSharp/GtkSharp/issues/104

**Closed by harry-cpp** 2020-03-27 23:48 UTC

**Comment by badcel** [comment] 2020-03-28 06:38
Hey I'm currently working on an alternative implementation of several gir libraries (including libhandy). 

For libhandy there ist currently only one example class (pagination). Adding new API ist very easy.

If you are interested take a look: https://github.com/GirCore/gir.core

Any help is welcome.
